language: java
jdk: openjdk11

before_install:
  - sudo apt-get update
  - sudo apt-get install -y mono-runtime

install:
  - ./gradlew clean bootWar

script:
  - ./gradlew build
  - ./gradlew dependencyUpdates
  - ./gradlew dependencyCheckAnalyze

cache:
  directories:
    - /home/travis/.gradle/dependency-check-data/4.0
